#!/bin/bash -e
if [ -a $1 ];then
echo 
else
   echo ' file do not exists';exit
fi
file=${1##*/}
if [  `whoami` = "root" ];then
echo
else
         echo "must be root!";exit
fi
if [ -a /mnt/sfpkg ];then
   echo
else
   mkdir /mnt/sfpkg
fi
if [ -a /mnt/sfpkg/$file ];then
echo
else
   mkdir /mnt/sfpkg/$file
fi
if [ -a /mnt/sfpkg/$file/auto.sh ];then
echo
else
   mount $1 /mnt/sfpkg/$file
fi
sh /mnt/sfpkg/$file/auto.sh /mnt/sfpkg/$file
exit
   
